@base_url = http://127.0.0.1:3000

###
GET {{base_url}}/users

###
POST {{base_url}}/auth/register
Content-Type: application/json

{
    "firstName": "Luiz",
    "lastName": "Leme",
    "email": "luiz.leme@estoqueprev.com.br",
    "password": "luiZ$1239"
}

###
POST {{base_url}}/auth/login
Content-Type: application/json

{
    "email": "luiz.leme@estoqueprev.com.br",
    "password": "luiZ$1239"
}

###
GET {{base_url}}/auth/profile
Authorization: Bearer 

###
PATCH {{base_url}}/users/
Content-Type: application/json

{
    "role": "ADMIN"
}