@base_url = http://127.0.0.1:3000

###
GET {{base_url}}/api/users

###
POST {{base_url}}/api/auth/register
Content-Type: application/json

{
    "firstName": "Luiz",
    "lastName": "Leme",
    "email": "luiz.leme@estoqueprev.com.br",
    "password": "luiZ$1239"
}

###
PATCH {{base_url}}/api/users/2210ed10-3843-4ef8-82b6-64b979de9d6a
Content-Type: application/json

{
    "role": "ADMIN"
}