name: 'api-estoque-prev'

services:
  pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=estoqueprev
  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - REDIS_MASTER_PASSWORD=docker
      - REDIS_PASSWORD=docker
