name: 'api-estoque-prev'

services:
  pg:
    image: bitnami/postgresql
    ports:
      -5432:5432
    environment:
      - POSTGRES_USERNAMEM=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRESS_DATABASE=estoqueprev
